$('.owl-carousel').owlCarousel({
    loop:true,
    margin:50,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        800:{
            items:3
        },
        1400:{
            items:3
        }
    }
})