$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:2
        },
        800:{
            items:5
        },
        1000:{
            items:7
        },
        1400:{
            items:9
        },
        1600:{
            items:12
        }
    }
})